abstract class States {}
class AppInitialState extends States{}
class AppChangenavbarState extends States{}
class AppChangebottomsheetState extends States{}
class AppCreateState extends States{}
class AppInsertState extends States{}
class AppDeleteState extends States{}
class AppUpdateState extends States{}
class AppGetDatabaseState extends States{}
class AppGetDatabaseLoadingState extends States{}